baseurl = "https://cmocanu.github.io/blog/"
languageCode = "en-us"
title = "cristian"
theme = "hugo-classic"
googleAnalytics = "UA-109214586-1"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[permalinks]
    post = "/post/:slug/"

[params]
    description = "Cristian's blog"
    footer = ""
